### PR TITLE
Update to RN26.1

### PR DESCRIPTION
**Pull request by wookiem**
Includes breaking changes -- see updated README.md.

### CODE REVIEW

**Comment by bartonhammond** [comment]
Well, I'm at a  loss to figure this out at this time.  Maybe someone else will.   I'll leave the PR incase someone wants to pick it up.

**Comment by wookiem** [comment]
If anyone wants to add support for Android, here are a couple of hints:
- Use the package.json, snowflake.js and container/component files that I provide.  They should be good.
- You can run "react-upgrade" as described here:
https://facebook.github.io/react-native/docs/upgrading.html

There are additional steps that are provided in the terminal output of react-native upgrade (i.e. need to run "rnpm upgrade".  So follow those as well.  

After all is said and done, there are 4 or 5 Android-specific project files that get touched, so those are the ones that can be contributed as an incremental PR to this one.

**Comment by sharq1** [comment]
@wookiem are your tests passing? I'm having problems with `Header` test.

**Comment by wookiem** [comment]
Header-test.js is passing, but the following are not:

1. authActions-test.js

- authActions › it should logout
 - TypeError: _reactNativeRouterFlux.Actions.Login is not a function

- authActions › it should getSessionToken
  - TypeError: _reactNativeRouterFlux.Actions.InitialLoginForm is not a function

2. LoginForm-test:
  - Error: Cannot find module './datepicker' from 'index.js'

3. ItemCheckbox-test.js
 - Error: Cannot find module './react-native' from 'create-icon-set.js'

**Comment by bartonhammond** [comment]
@wookiem I have some time now to address this.  But I'm going for RN 29. So I'll start from the master and see what I can do.

**Comment by wookiem** [comment]
Sounds good Barton.

**Comment by bartonhammond** [comment]
I ran into the RN 25 upgrade issues yesterday so I really appreciate you
already teased out the declarations.  What a pain for those with a large
project!  I will be pulling a lot of your code over.  I see you added Buck
support.  It's a build environment, right?  What was your motivation given
Bitrise.io already builds Snowflake?  Just wondering as I have no
experience with Buck.  Thoughts?

**Comment by wookiem** [comment]
Great, hopefully will save you some time.

I believe that I needed Buck when I was playing around with the Nuclide
IDE.  So, there shouldn't be any reason to add it to Snowflake.

**Comment by bartonhammond** [comment]
Argh, I'm finally back on this.  iOS works fine but not Android. @wookiem,  Did you happen to test on a Android emulator?  I'm having a problem w/ the SimpleAlertAndroid module - but only on Android.

**Comment by wookiem** [comment]
Sorry, Barton -- all my development has been on iOS so far.

**Comment by bartonhammond** [comment]
NP - It looks like maybe it's just an installation thing wrt Android.

**Comment by bartonhammond** [comment]
Status: I've upgraded the app to run w/ RN 0.29.2.  Wow...that was fun (not).  

One problem I'm having right now that you might know how to work through, when I run ```react-native run-ios``` I can bring up the developer menu w/ Cmd-D but then I can't select any of the options!

I've tried changing the hardware settings to no avail.

Any suggestions on how to debug?

Thanks in advance...oh - it was much easier to just work directly in this pull request.  Hopefully I haven't made a mess w/ merging...I'll address that later...hopefully ;)

**Comment by bartonhammond** [comment]
Ignore previous problem w/ debugging....soon as I toggled back it started working.  Maybe it's time to take a break???

**Comment by wookiem** [comment]
Yeah, it was not fun at all and you've gotten a lot further than I did.
Well, the good news is that the end is in sight :)

The git merge did throw up a couple of project files that required some
dicey hand-merging. On the iOS side, you can look at the merge decisions I
made on snowflake.xcodeproj/project.pbxproj.

Kevin

**Comment by bartonhammond** [comment]
What I'm thinking is to move the .git from Snowflake to your branch and
check that in to avoid any merge issues.  But first today I need to look at
testing.

I will try to update your forked repo and go that way but if problems...

I might not have got this w/o your contribution!!!

**Comment by bartonhammond** [comment]
@wookiem Thanks...I'm so grateful for your contributions Kevin.

**Comment by wookiem** [comment]
Wow, you're on a roll today!  Thanks for diving back in and getting it
mostly caught up.

**Pull request merged**
