### PR TITLE
Upgrade bitrise-android.yml so signing is done with a persistent key

### PR DESCRIPTION
**Pull request by larubbio**
Signing is now done using bitrise.io's sign-apk step.  This also includes some updates of versions of steps and tools.

- Upgrade git-clone workflow step
- Upgrade to node 5
- Remove call to keytool and steps for copying the keystore
- Remove install of android sdk since it is included in the bitrise vm
- Remove params to gradlew since we are no longer signing in the compile step
- Remove copy and restore of build.gradle since we can use the unsigned version now
- Add bitrise sign-apk step
- Update copy step so it renames the apk to show it is now signed.
- Upgrade deploy-to-bitrise step version
- Delete no longer needed build.gradle.sign

### CODE REVIEW

**Comment by bartonhammond** [comment]
I'm testing on Bitrise

I get error on "sign-apk": ```Error: Missing required input: keystore_url```

**Comment by larubbio** [comment]
You have to upload you key first.  In the UI below Workflow Editor and above Secret Env Vars you should see Code Signing & Files.  If you upload your keystore, setting the type to android keystore, then bitrise will define some variables for you that the sign-apk step needs.

**Comment by bartonhammond** [comment]
I haven't work w/ this Android build since I first did it - remind me where/how I get my keystore?

**Comment by bartonhammond** [comment]
Ignore - I've got it (i think)

**Comment by larubbio** [comment]
You have to first generate it locally by running keytool.  You can take the
command out of the old bitrise-android.yml file.  It's essentially this
command:

```
keytool -genkey -noprompt -alias $SNOWFLAKE_RELEASE_KEY_ALIAS -dname "CN=
snowflake.bartonhammond.org, OU=bartonhammond.org, O=Unknown, L=Austin,
ST=TX, C=US" -keystore $SNOWFLAKE_RELEASE_STORE_FILE -storepass
$SNOWFLAKE_RELEASE_STORE_PASSWORD -keypass $SNOWFLAKE_RELEASE_KEY_PASSWORD
```

That will output a file called $SNOWFLAKE_RELEASE_STORE_FILE which you then
upload in bitrise.  You'll also want to save that file someplace safe since
it holds the key that your app is signed with.

**Comment by bartonhammond** [comment]
Yeah - that's what I did - took me a while to remember...

**Pull request merged**
