### PR TITLE
Reduce the boilerplate code of mapDispatchToProps functions

### PR DESCRIPTION
**Pull request by moduv5**

### CODE REVIEW

**Comment by bartonhammond** [comment]
@moduv5 Thanks for addressing this!  I appreciate this very much.

I'm not sure why these PRs were done as 2 separate PRs but the situation now is there are conflicts w/ this particular PR.  I'm not able to get things working.  The Android Genymotion is missing the icons for the Tabbar for example and a couple of the files had conflicts.

Would you mind fixing this PR so that there are no conflicts and verify that both Android and iOS still work the same?

**Comment by moduv5** [comment]
@bartonhammond Do I have to setup all the backend to be able to test this? I'm able to open the app but can't pass through the register form because I do not have a backend setup.

**Comment by bartonhammond** [comment]
It would be best to have a backend to verify all the actions were mapped
correctly.

If you've resolved the conflicts and `npm test` passes, let me look at it
again since I have a backend ready.  If I run into issues, I would suggest
that you setup a backend and help figure out what changed.

But for now, if there are no conflicts, I can give it a whirl.

**Comment by moduv5** [comment]
@bartonhammond I fixed the merge conflicts and all test passes.

**Comment by bartonhammond** [comment]
Ok - I'll give it a go!

**Comment by bartonhammond** [comment]
Well - something is wrong.  I can't log in now using the master branch.

On my server log I have
```

Server is running: http://Bartons-MBP:5000

160817/105941.144, [response], http://Bartons-MBP:5000: post
/account/logout {} 200 (35ms)

Debug: internal, implementation, error

    TypeError: Cannot read property 'password' of null

    at
/Users/barton/projects/snowflakework/snowflake-hapi-openshift/src/routes/account/handlers.js:99:28

    at Query.<anonymous>
(/Users/barton/projects/snowflakework/snowflake-hapi-openshift/node_modules/mongoose/lib/model.js:3331:16)

    at
/Users/barton/projects/snowflakework/snowflake-hapi-openshift/node_modules/kareem/index.js:259:21

    at
/Users/barton/projects/snowflakework/snowflake-hapi-openshift/node_modules/kareem/index.js:127:16

    at _combinedTickCallback (internal/process/next_tick.js:67:7)

    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

And in `src\containers\Login.js`  I did the following:

```


function buttonPressHandler(login, username, password) {

  console.log('buttonPressHandler.username',username);

  console.log('buttonPressHandler.password',password);

  login (username, password);

}
```
And the console.log looks like this:
```
buttonPressHandler.username Barton
index.android.bundle:98761buttonPressHandler.password Passw0rd!
```

I'm really baffled as I was testing your first PR and everything was fine.

I have an committment now and won't be able to look at this until later.

Something else I've noticed is that w/ a fresh install, the
`react-native-vector-icons` are missing from the Android.

I don't think that has anything to do w/ your PRs but it does concern me as
I know I addressed this just a couple of days ago.

**Comment by moduv5** [comment]
If my first pull request was working fine, I don't think it have something to do with this pull request as I only change how the actions are bind in the components not how they are use.

**Comment by bartonhammond** [comment]
Agree.  Don't worry bout it.  When I get back home I can focus on this.
I'm positive what I'm seeing has something to do with renaming a directory
by down casing Fonts to fonts.  I'll be back late this evening.

**Comment by bartonhammond** [comment]
Wow...that was weird - I had to delete out the `android/**/build` directories to get the icons to show on the toolbar (nothing to do w/ your code).

Thanks @moduv5 - I really appreciate this

**Pull request merged**
