### PR TITLE
Add support for parse-server

### PR DESCRIPTION
**Pull request by wookiem**

### CODE REVIEW

**Comment by bartonhammond** [comment]
Did you address email confirm and reset password?  The server should be
functionally equivalent.

**Comment by wookiem** [comment]
Yes, I'm using Mailgun which is the default email adapter for Parse Server.  Email confirmation and password reset are both working.

**Comment by wookiem** [comment]
Further documentation on this as well as other email adapters are available at:
https://github.com/ParsePlatform/parse-server

**Comment by bartonhammond** [comment]
My concern is documenting all the setup issues for the server.  Would it be helpful to have a repo with all the configuration setup done?  That way, for Snowflake, they could get a local server running quickly.  What do you think?

**Comment by wookiem** [comment]
Yes, that should work.  I'm away for the weekend, so I'll pick this up next week.

**Comment by bartonhammond** [comment]
Thanks.

**Comment by bartonhammond** [comment]
@wookiem - I'd like to bring this in but I'm still waiting on a "snowflake parse server" being made available, one that has all the emails (forgot password and email verification) functionality.  If you don't want to maintain that w/ your own repo, I would be glad to hoist it on my account and keep it up to date.  What are your thoughts?

**Comment by wookiem** [comment]
Hi Barton.  Sorry for the delay.  I've been tied up preparing for a demo and so just getting back to this now.

It makes sense to keep everything under your repo.  I'll fork parse-server-example and apply my changes, then you can fork my repo.  

You'll need to create a Mailgun account for your fork.  Mailgun permits up to 10,000 free emails per month.  They *don't* require credit card information for sign-up.  Hopefully people don't hammer on Mailgun to the point that it exceeds monthly allowance.

I should be able to complete this by tomorrow.

**Comment by bartonhammond** [comment]
Sounds good...thanks

**Comment by wookiem** [comment]
Just a quick update...

I've successfully setup parse-server running on Heroku and it works fine when I configure Mailgun to use my company-owned domain.  However, no success so far getting it to use a new gmail account that I set up for this purpose (snowflakeparse@gmail.com).  I've sent in a support request to mailgun, but nothing back as of yet.

Fyi, I initially chose Heroku a few months ago because they were one of the first with parse-server support.  They also have a streamlined flow for setting up parse-server (it auto-installs a MongoDB at mlabs).  I'm using a free tier of service at Heroku / MongoDB.

**Comment by bartonhammond** [comment]
I ran into this with the Hapi Snowflake server, check out the setup for
gmail here https://github.com/nodemailer/nodemailer/blob/master/README.md

**Comment by bartonhammond** [comment]
Specifically
> To use Gmail you may need to configure "Allow Less Secure Apps" in your
Gmail account unless you are using 2FA in which case you would have to
create an Application Specific password. You also may need to unlock your
account with "Allow access to your Google account" to use SMTP.
Setting up

**Comment by wookiem** [comment]
I can't figure out how to configure "allow access to your google account" to use SMTP from a free gmail account.  I do see you can configure a g-suite account, but afaik g-suite requires a custom domain name as well.  Mailgun informs me that I need to use my own domain name as well.  

Did you end up using a gmail account as your "sent from" address in your hapi setup?

**Comment by bartonhammond** [comment]
Yes

**Comment by wookiem** [comment]
I've setup a custom domain as a workaround.  It will take a day or two for the MX records to propagate so I can continue with the mailgun setup.

**Comment by wookiem** [comment]
Here's the snowflake customized version of parse-server example:
https://github.com/wookiem/parse-server-example

I found a bug in this PR, so I'll push the updates shortly...

**Comment by wookiem** [comment]
Ok, I've pushed my bug fixes to this PR

**Comment by bartonhammond** [comment]
Thanks for update.

**Comment by bartonhammond** [comment]
What is your opinion?  Should I fork your project or copy it? I think users should see the project as an 'original' in this repo but I don't want to lose the "forked" from parse-server.  Do you know how to achieve that?  If I am going to maintain this going forward, it seems that I should *not* fork your repo.  Maybe I'm missing something.  What do you think?

**Comment by wookiem** [comment]
I think it can be its own separate repo. It was originally a clone of parse-server-example which in turn adds setup automation / hooks into 5 or so hosting environments for parse-server. 

I have simply:
- Selected one of the hosting environments (Heroku) and provided a much more detailed step-by-step recipe for setting everything up
- Explicit instructions on how to configure the Snowflake app for both a locally running and hosted parse-server environment

So feel free to create a new repository (parse-server-for-snowflake?) and copy everything across, but you should probably:

- Cite parse-server-example as the source for the integration automation with Heroku.
- Indicate that parse-server-example offers integrations with several other hosting environments if Heroku isn't your first choice.

**Comment by bartonhammond** [comment]
Ok, sounds goood.  I hope to work on this in the next couple of days.

**Comment by wookiem** [comment]
Sounds good.

**Comment by bartonhammond** [comment]
I'm good w/ all this now.  I tested against your heroku app.  Once I get the parse-server working w/ my domain, I'll finish it all up.  This might take a couple of days as I have to transfer a domain and all that.

**Comment by wookiem** [comment]
Good stuff.  Thanks for the update.

**Comment by bartonhammond** [comment]
@wookiem, Question: I am in process of moving my domain to NameCheap.  I plan on adding Hosting and that will give me 3 websites.  Rather then hosting the `snowflake-parse-server` on Heroku, do you know if it could be hosted on NameCheap?

**Comment by wookiem** [comment]
Looks like my response from earlier today got lost with the DoS on GitHub earlier today...

You may be able to host parse-server on NameCheap, but I don't think I'd point other users to go this route.  Heroku (and likely the other service providers identified on parse-server-example) have really optimized the configuration flow around parse-server.  

For example, the one-click Heroku deployment kicks-off an enrollment process which:
- One-click launch directly into the Heroku setup process for parse-server
- automatically configures a MongoDB at mlabs without any further user involvement.  
- Asks users to configure parse-server environment variables within the enrollment process

From a cost standpoint, you'd can host parse-server on Heroku using their free tier of service.  So there shouldn't be any cost advantage to using NameCheap over Heroku.

**Comment by bartonhammond** [comment]
Thanks for the response - I didn't know all that.  Makes sense.  

I'm waiting now for GoDaddy to transfer my domain to NameCheap so I can have emails cheaply.

**Comment by amilajack** [comment]
@bartonhammond I would recommend google domains :)

**Comment by wookiem** [comment]
I'd stick with one the 5 or so hosted environments identified in
parse-server-example.  Heroku offers a free tier of service which should be
fine for this situation. Also, by clicking the Heroku setup button, it
automatically installs MongoDB at mlab for you, so it's one less piece of
infrastructure for the user to have to install and manage.

**Comment by bartonhammond** [comment]
I'm staying with exactly your project setup.  I'm waiting on NameCheap now
and traveling.  Not sure what the time frame will be.

**Comment by wookiem** [comment]
That works.

**Comment by bartonhammond** [comment]
@wookiem - I've got Mailgun setup now and am starting on the Heroku app.   

Do you need the `snowflake-parse` app name?  Would you be interested in deleting that app and letting me take the name?

**Comment by wookiem** [comment]
Ok, just freed up that name...

**Comment by bartonhammond** [comment]
Thanks!

**Comment by bartonhammond** [comment]
@wookiem: Status 
Remote works great!  Emails work fine, but where is the logic / templates for the emails?

Local is not good.  From the command line I get the following log which appears to stop the app from running.  Did you run into this when running locally?

```
parse-server-example running on port 1337.
info: Parse LiveQuery Server starts running
warn: Unable to ensure uniqueness for usernames:  MongoError: failed to connect to server [ds137267.mlab.com:27017] on first connect
    at .<anonymous> (/Users/barton/projects/snowflakework/snowflake-parse-heroku/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/Users/barton/projects/snowflakework/snowflake-parse-heroku/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/Users/barton/projects/snowflakework/snowflake-parse-heroku/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
warn: Unable to ensure uniqueness for user email addresses:  MongoError: failed to connect to server [ds137267.mlab.com:27017] on first connect
    at .<anonymous> (/Users/barton/projects/snowflakework/snowflake-parse-heroku/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/Users/barton/projects/snowflakework/snowflake-parse-heroku/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/Users/barton/projects/snowflakework/snowflake-parse-heroku/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)

```

**Comment by wookiem** [comment]
Regarding email templates...  You can modify the default HTML email templates here:

`node_modules/parse-server/public_html`

I also found this, but I've not investigated:
https://github.com/mailgun/transactional-email-templates

**Comment by bartonhammond** [comment]
Sorry, I wasn't clear....Where do you have these "email verification" and
"reset password" emails defined?

**Comment by wookiem** [comment]
The password reset and email verification emails are built-in/managed by parse-server itself (i.e. just like parse.com).

**Comment by bartonhammond** [comment]
doh!  thanks.

Did you have problems running locally?  I can't figure out what's wrong.
Add my 2c here: https://github.com/ParsePlatform/parse-server/issues/2699

**Comment by bartonhammond** [comment]
I'm getting confused w/ all the settings and multiple projects...My problem w/ the MongoDB thing is now fixed (bad copy/paste)

Still can't connect the dashboard locally...

**Comment by bartonhammond** [comment]
Yeah - I updated the `package.json` for local and remote.  

Here's local server log:
```
> snowflake-parse-heroku@0.0.1 start /Users/barton/projects/snowflakework/snowflake-parse-heroku
> node index.js

verbose: Support key pairs Map {}
parse-server-example running on port 1337.
info: Parse LiveQuery Server starts running
```

Then for the dashboard:
```
~/projects/snowflakework/parse-dashboard (master)$ npm run local

> parse-dashboard@1.0.19 local /Users/barton/projects/snowflakework/parse-dashboard
> node ./Parse-Dashboard/index.js --appId snowflake --masterKey myMasterKey --serverURL http://0.0.0.0:1337/parse

The dashboard is now available at http://0.0.0.0:4040/
```

The dashboard says "server not reachable"

**Comment by wookiem** [comment]
That looks good.  

Maybe try --serverURL http://localhost:1337/parse 

Do you have parse-dashboard working with remote?

**Comment by bartonhammond** [comment]
Yeah - `parse-dashboard` works w/ remote just fine.

On local, when I debug the `lib/Parse.js` for the `login` method, the `res.status` has 404.

Likewise, if I try `http://localhost:1337/parse/login?username=barton&password=Passw0rd!` in browser, I get response `Cannot GET /parse/login?username=barton&password=Passw0rd!`

If I try `http://localhost:1337/` I get `I dream of being a website. Please star the parse-server repo on GitHub!`

**Comment by bartonhammond** [comment]
Did you have to do something in iOS to allow `http` rather then `https`?

**Comment by bartonhammond** [comment]
I tried w/ Android and get same '404' error.

**Comment by wookiem** [comment]
No, I didn't do anything special.  In my snowflake config.js file, I put in the actual IP address for the parse-server (i.e. not localhost):

```
module.exports = {
  SESSION_TOKEN_KEY: 'SESSION_TOKEN_KEY',
  backend: {
    hapiRemote: false,
    hapiLocal: false,
    parseRemote: true,
    parseLocal:  false
  },
  PARSE: {
 		appId: 'snowflake',
 		masterKey: 'myMasterKey',    // match APP_ID in parse-server's index.js
    local: {
    	url: 'http://192.168.0.15:1337/parse',            	// match SERVER_URL in parse-server's index.js
    },
    remote: {
    	url: 'https://snowflake-parse.herokuapp.com/parse'		// match SERVER_URL in parse-server's index.js
    } 		
  }
}
```

**Comment by wookiem** [comment]
You can use curl to confirm parse-server is working:

```
curl -X POST \
-H "X-Parse-Application-Id: snowflake" \
-H "Content-Type: application/json" \
-d '{"score":1337,"playerName":"Sean Plott","cheatMode":false}' \
http://localhost:1337/parse/classes/GameScore
```

**Comment by bartonhammond** [comment]
I'm out now, when I get home I'll look at - to use ip.  Thanks.

**Comment by bartonhammond** [comment]
got response: `Cannot POST /parse/classes/GameScore`

**Comment by bartonhammond** [comment]
wow - env variable `PARSE_MOUNT` requires forward slash:

this: `/parse`
not: `parse`

**Comment by wookiem** [comment]
Good catch.

**Pull request merged**
