### PR TITLE
Try to have tests also check the number of actions in addition to the order

### PR DESCRIPTION
**Pull request by larubbio**
This change doesn't work correctly, I'm just creating the pull request so it can be discussed.

The issue is that since action handlers my return functions which in turn create promises I'm not sure how to tell when all of the promises have been resolved.  Since I can't tell when they have all been resolved the count can be off by one or more.

### CODE REVIEW

**Comment by larubbio** [comment]
The tests should be passing on this now.   Using jest.runAllTimers allows the promises to resolve and we can then verify that all of the expected events are dispatched.

Also just for fun I added a test for a failed login.

**Comment by bartonhammond** [comment]
@larubbio 

I changed ```authActions-test.js``` as such (adding an expected action that doesn't happen)

```
 it('should login', () => {
    const expectedActions = [
      {type: LOGIN_REQUEST},
      {type: LOGIN_STATE_LOGOUT},
      {type: LOGIN_SUCCESS},
      {type: LOGIN_SUCCESS}   ///<<<<<<<<<<<<<<<<shouldn't happen
    ];

    const store = mockStore({}, expectedActions);
    return store.dispatch(actions.login('foo','bar')).then(() => {
      jest.runAllTicks();
      expect(store.getExpectedActionCount()).toEqual(store.getActualActionCount());
    });
  });
```

And it still passed.

**Comment by larubbio** [comment]
I am not a fan of jest.  The promise of "PAINLESS JAVASCRIPT UNIT TESTING" is a blatant lie.  

According to their docs runAllTimers "... is often useful for synchronously executing all pending promises in the system."  It isn't doing that since I call it but it returns before all pening promises have been exhausted.  grrrrr....

**Comment by larubbio** [comment]
Converting the tests from it to pit resolves that issue.  Currently with them as it it only tests the first expected action.  In some cases the order of the actions in the code has changed and the tests were failing.

Still have an issue where a promise that creates a promise doesn't resolve.  As it is I'm not really sure how to test this code since jest.runAllTimers isn't doing what I hoped it would.

**Comment by larubbio** [comment]
In the logout() action, deleteSessionToken() returns a promise.  If logout returns that then the promise
chain remains intact which allows pit to wait for it to complete.  

There are a couple of problems with this, it requires internal knowledge of the other actions functions which is fragile.  If logoutSuccess() is modified to use a promise then this all starts failing until the code in logout is modified to look like this:

```
      .then(() => {
        dispatch(registerState());
        return dispatch(logoutSuccess());
      })
      .then(() => {
        return dispatch(deleteSessionToken());
      })
```

Of course if logoutSuccess is then changed back to not using a promise then I think this code will blow up since it wouldn't be returning a thenable object.

So not ideal but I think this might test the code now.

**Comment by larubbio** [comment]
Just an FYI on my local version I switched from this custom mock store to [redux-mock-store](https://www.npmjs.com/package/redux-mock-store)  Also according to the redux testing [docs](http://redux.js.org/docs/recipes/WritingTests.html) I switched from jest to mocha and am using nock instead of mocks for the backend api calls.  The nice thing about that is I can easily vary the return from the api calls.

That change also requires switching the way the json body is received.  Instead of using `response._bodyInit` which I'm not sure is part of the official api I had to use `response.json()` like this:

```
      .then((response) => {
        let json = response.json();
        if (response.status === 200) {
          return json;
        } else {
          return json.then(err => {throw err;});
        }
      })
      .then((json) => {
          return json;
      })
      .catch((error) => {
          throw(error);
      });
```

I'm not sure all of that is needed to get this functioning, but I would imagine moving to redux-mock-store and using jasmine1 runs and waitsFor or jasmine2 done callback would get this running more reliably.

I'm not sure I'll do more work on this pull request, so you can close and ignore or open tickets for the other changes above if you want.

**Comment by bartonhammond** [comment]
@larubbio Thanks for looking into this!  

Unfortunately [https://github.com/arnaudbenard/redux-mock-store](https://github.com/arnaudbenard/redux-mock-store) depends on Mocha and I'm not moving off of Jest as that is the Official testing for React according to Facebook, see [https://facebook.github.io/react-native/docs/testing.html](https://facebook.github.io/react-native/docs/testing.html).

I've raised the issue of no 'standard' way of doing Jest testing of React-Native with the Jest testing lead Christoph Pojer.  He has stated he has plans to address all of this - https://twitter.com/bartonhammond/status/702486997529600000

**Pull request closed without merging**
