### PR TITLE
Added support for eslint-plugin-flowtype-errors

### PR DESCRIPTION
**Pull request by amilajack**
- [x] Added Flow support with `eslint-plugin-flowtype-errors`
- [x] Extended `eslint-config-standard`
- [x] Added jest global variables to eslint

### CODE REVIEW

**Comment by bartonhammond** [comment]
I think we're missing a node_module?

```
~/projects/snowflakework/snowflake-eslint (amilajack-add-eslint-flowtype-errors-support)$ npm run lint

> snowflake@0.1.11 lint /Users/barton/projects/snowflakework/snowflake-eslint
> eslint . --fix --ignore-path .gitignore --format=node_modules/eslint-formatter-pretty

There was a problem loading formatter: /Users/barton/projects/snowflakework/snowflake-eslint/node_modules/eslint-formatter-pretty
Error: Cannot find module '/Users/barton/projects/snowflakework/snowflake-eslint/node_modules/eslint-formatter-pretty'

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! snowflake@0.1.11 lint: `eslint . --fix --ignore-path .gitignore --format=node_modules/eslint-formatter-pretty`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowflake@0.1.11 lint script 'eslint . --fix --ignore-path .gitignore --format=node_modules/eslint-formatter-pretty'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snowflake package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint . --fix --ignore-path .gitignore --format=node_modules/eslint-formatter-pretty
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snowflake
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls snowflake
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/barton/projects/snowflakework/snowflake-eslint/npm-debug.log
~/projects/snowflakework/snowflake-eslint (amilajack-add-eslint-flowtype-errors-support)$ 

```

**Comment by bartonhammond** [comment]
Also, would you please update the `README.md` with instructions for using this with some editor?  I do not know how to test this w/ Emacs which I use.

**Comment by amilajack** [comment]
Good idea. I'll add that. Also I have a question about [this line](https://github.com/bartonhammond/snowflake/blob/master/package.json#L29). What is the `./node_modules/standard/bin/cmd.js` line doing? Is it trying to run standard?

**Comment by amilajack** [comment]
> I do not know how to test this w/ Emacs which I use.

According to the eslint docs, here's how you can add support for it:

screen shot 2016-10-17 at 9 26 13 am

**Comment by bartonhammond** [comment]
I know what the steps are for Emacs.

If we're going to add this, I want the README to have some indication that
this functionality has been added to the project.  You could add that above
section, for example, to the README.  Initially you showed me a animated
gif showing how the eslint was being used.  I'd really like something like
that showing Snowflake being edited.

Maybe in the Content section (
https://github.com/bartonhammond/snowflake#content) we could have a link
for setting up an editor and show the animated gif along w/ that section
above.

**Comment by amilajack** [comment]
Migrated discussion to https://github.com/bartonhammond/snowflake/pull/156

**Pull request closed without merging**
