### PR TITLE
Add missing whatwg-fetch dependency

### LINKED ISSUE #180: Missing dependency whatwg-fetch
When I tried to run `npm install` I got 
image

The issue is solved simply running `npm install whatwg-fetch@^1.0.0 --save-dev` or adding `"whatwg-fetch": "^1.1.1"` to package.json, I tried to send a PR but I wasn't able to do so.

### PR DESCRIPTION
**Pull request by siemiatj**
Someone noticed that this dependency is missing.

Fixes #180

### CODE REVIEW

**Comment by bartonhammond** [comment]
Thanks..I will like at soon ..

**Comment by bartonhammond** [comment]
Look...

**Comment by siemiatj** [comment]
I'm not authorized to check the failing bitrise build.

**Comment by bartonhammond** [comment]
Yeah, Bitrise changed their android stack, I need to figure the new setup.

**Comment by bartonhammond** [comment]
This does not occur now w/ the latest upgrade to Snowflakea; https://github.com/bartonhammond/snowflake/releases/tag/0.2.1

Thanks for looking into this!

**Pull request closed without merging**
