### PR TITLE
Update deps, add eslint-plugin-flowtype-errors support

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by bartonhammond** [comment]
Would you please delete the original PR if it is no longer needed?

**Comment by amilajack** [comment]
Moved the discussion here

**Comment by amilajack** [comment]
>   I'd really like something like that showing Snowflake being edited.

I'm not really good at recording screen recording but I'll try this out. Also I should note that if we include the gif in this repo, it might slow down clone speeds. Maybe if we could upload it to a different server? Like dropbox or something?

**Comment by bartonhammond** [comment]
So skip for now.  I will look into it.

**Comment by bartonhammond** [comment]
I won't be able to work on this until tomorrow...thanks, it looks good.  I have too much going on today.

**Comment by amilajack** [comment]
No worries!

**Comment by amilajack** [comment]
How about this?

https://www.dropbox.com/s/ob0gpzpia340pd6/Untitled.mov?dl=0

**Comment by bartonhammond** [comment]
Good job @amilajack - I really appreciate your contribution!

**Comment by bartonhammond** [comment]
Just saw the movie - missed that.  What editor is that?

**Comment by amilajack** [comment]
It is atom editor with this theming configuration:

screen shot 2016-10-18 at 1 40 30 pm

**Pull request merged**
